theme: jekyll-theme-cayman
title: "Group89 - Platform Esports & Game"
description: "Platform berbagi pengetahuan tentang esports dan strategi permainan."
url: "https://group89-github.io"  # Pastikan URL ini sesuai dengan GitHub Pages Anda.
baseurl: ""
paginate: 5

# Author and settings
author: 
  name: "GROUP89"
  email: "hanyagroup89@gmail.com"

# Social Media
social:
  github: "https://github.com/Group89"
  twitter: "https://twitter.com/Group89"
  linkedin: "https://www.linkedin.com/company/group89"
